version: '3'

services:
  pthreads:
    build:
      context: .
      dockerfile: ./01-pthreads/Dockerfile
    image: docker.io/entrega_cpd_2024_pthreads

  openmp:
    build:
      context: .
      dockerfile: ./02-openmp/Dockerfile
    image: docker.io/entrega_cpd_2024_openmp

  openmpi:
    build:
      context: .
      dockerfile: ./03-openmpi/Dockerfile
    image: docker.io/entrega_cpd_2024_openmpi

